import React from "react";
import Footer from "../Footer";
import { useNavigate } from "react-router-dom";

const SolarwindPage = () => {
  const navigate = useNavigate();
  const handleHome = () => {
    navigate("/");
  };
  return (
    <>
      <div className="relative h-screen bg-gray-900 text-white overflow-hidden">
        {/* Background Image */}
        <div className="absolute inset-0 z-0">
          <img
            src="https://d.newsweek.com/en/full/2115191/magnetic-field.webp?w=1400&f=9ab4c19225251850bf199723f1df9524"
            alt="Rivian vehicle"
            className="w-full h-full object-cover opacity-85"
          />
        </div>

        {/* Content Overlay */}
        <div className="relative z-10 h-full flex flex-col">
          {/* Header */}
          <header className="flex justify-between items-center p-6">
            <div className="text-2xl font-bold font-[Rejoy]">Spacifyer</div>
            <button
              onClick={handleHome}
              className="text-xl font-bold mt-6 font-mono"
            >
              Home
            </button>
          </header>

          {/* Main Content */}
          <main className="flex-grow flex items-end">
            <div className="w-full p-8">
              <h1 className="text-4xl md:text-6xl font-bold leading-tight text-right max-w-3xl ml-auto align-middle w-[27rem]">
                The solar wind is a continuous stream of particles, mostly
                protons and electrons, that flow from the sun.
              </h1>
            </div>
          </main>

          {/* Navigation Arrows */}
          <div className="absolute left-4 top-1/2 transform -translate-y-1/2">
            <button className="text-4xl opacity-50 hover:opacity-100 transition-opacity">
              &#8592;
            </button>
          </div>
        </div>
      </div>
      <div className="bg-black text-white min-h-screen font-sans">
        {/* Header */}

        {/* Main Content */}
        <main className="px-6 py-12 md:py-24 flex flex-col md:flex-row justify-between mt-[60px]">
          {/* Services Section */}
          <div className="md:w-1/3 mb-8 md:mb-0">
            <h2 className="font-bold mb-4 font-[rejoy]">
              Source:{" "}
              <a
                className="text-orange-500 hover:text-orange-300 font-[rejoy]"
                href="https://www.nesdis.noaa.gov/our-environment/solar-activity/solar-wind-geomagnetic-storms-and-coronal-mass-ejections#:~:text=The%20solar%20wind%20is%20a,winds%20bring%20calm%20space%20weather."
              >
                www.nesdis.noaa.gov
              </a>
            </h2>
          </div>

          {/* Description Section */}
          <div className="md:w-2/3">
            <p className="text-lg mb-8">
              The Earth has a magnetic field, generated by movements within its
              molten core. This field extends into space and acts as a shield,
              deflecting the solar wind. However, when intense bursts of solar
              wind, often associated with coronal mass ejections (CMEs) or solar
              flares, hit Earth’s magnetic field, they can disturb this balance
              and lead to geomagnetic storms.
            </p>
            <div className="text-2xl ">Scroll Down For More ⬇️</div>
          </div>
        </main>
        <div className="bg-black text-white py-16">
          <div className="container mx-auto px-4 flex flex-col md:flex-row items-center">
            {/* Image on the left */}
            <div className="md:w-1/2 mb-8 md:mb-0">
              <img
                src="https://www.aeronomie.be/sites/default/files/2019-07/SolarWind_CreditsNASA-lores_36652_1.jpg"
                alt="Geomagnetic Storm"
                className="w-full h-auto rounded-lg shadow-lg"
              />
            </div>

            {/* Text on the right */}
            <div className="md:w-1/2 md:pl-8">
              <h2 className="text-3xl font-bold mb-4">
                Arrival Of Solar Wind At Earth
              </h2>
              <p className="text-lg mb-4">
                Once the solar wind, carrying the charged particles and magnetic
                fields, reaches Earth, it interacts with our planet’s magnetic
                field (the magnetosphere). This typically happens 1-4 days after
                a CME, depending on its speed, or in minutes to hours after a
                solar flare. Normal Solar Wind Interaction: Under normal
                conditions, Earth’s magnetic field deflects most of the solar
                wind, keeping it at a safe distance. Disturbed Solar Wind
                Interaction: However, if a CME or flare is strong enough, the
                increased speed and density of the solar wind overwhelms the
                Earth’s magnetosphere, causing significant disturbances.
              </p>
            </div>
          </div>
        </div>
        <div className="bg-black text-white py-16">
          <div className="container mx-auto px-4 flex flex-col md:flex-row items-center mt-[55px] mr-[45px]">
            {/* Image on the left */}
            {/* Text on the right */}
            <div className="md:w-1/2 md:pl-8">
              <h2 className="text-3xl font-bold mb-4">Magnetic Reconnection</h2>
              <p className="text-lg mb-4">
                One of the key processes that triggers a geomagnetic storm is
                magnetic reconnection. This occurs when the magnetic field
                carried by the solar wind connects with the Earth’s magnetic
                field. During reconnection: The solar wind's magnetic field
                merges with Earth's magnetic field. This process transfers
                energy from the solar wind into Earth’s magnetosphere,
                increasing its overall energy and causing disturbances. As more
                energy is pumped into the magnetosphere, it becomes highly
                disturbed, leading to the formation of geomagnetic storms.
              </p>
            </div>
            <div className="md:w-1/2 mb-8 md:mb-0">
              <img
                src="https://scx2.b-cdn.net/gfx/news/2021/when-the-solar-wind-hi.jpg"
                alt="Geomagnetic Storm"
                className="w-full h-auto rounded-lg shadow-lg"
              />
            </div>
          </div>
        </div>
        <div className="bg-black text-white py-16">
          <div className="container mx-auto px-4 flex flex-col md:flex-row items-center mt-[55px]">
            {/* Image on the left */}
            <div className="md:w-1/2 mb-8 md:mb-0">
              <img
                src="https://www.nasa.gov/wp-content/uploads/2023/03/470162main_magnetosphere-orig_full.jpg"
                alt="Geomagnetic Storm"
                className="w-full h-auto rounded-lg shadow-lg"
              />
            </div>

            {/* Text on the right */}
            <div className="md:w-1/2 md:pl-8">
              <h2 className="text-3xl font-bold mb-4">
                Energy Transfer Into The Magnetosphere
              </h2>
              <p className="text-lg mb-4">
                The energy from the solar wind is stored in Earth's magnetic
                tail (the portion of the magnetosphere that is stretched away
                from the Sun). Eventually, this energy is released, driving
                currents in the magnetosphere and ionosphere (the upper layer of
                Earth’s atmosphere, filled with charged particles).
              </p>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default SolarwindPage;
